### ISSUE TITLE
datetimepicker doesn't work

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio-contrib/solidus_sale_prices#19]
jquery picker has been removed from solidus 2.5, after that version solidus use flatpickr as datepicker, it needs to be changed to work with DateTime.

**Comment by spaghetticode** [comment]
@DanielePalombo can this be closed after https://github.com/solidusio-contrib/solidus_sale_prices/pull/21?

**Comment by DanielePalombo** [comment]
We can close it! Thanks.
