### ISSUE TITLE
Doesn't work with products with variants

### ISSUE THREAD

**Issue by ignaciosm** [solidusio-contrib/solidus_sale_prices#27]
I'm having problems when creating promotions for products with variants? 

The extension works well with products with no variants, but when I apply (put_on_sale) to a product with variants (even using 'all_variants = true') I get an error: "undefined method `compute' for nil:NilClass"

In the console by doing Spree::Product.find(123).variants.last.on_sale? I get 'true' so the sale should be applied. But when I do something like: Spree::Product.find(123).variants.last.sale_price 
I get 'NoMethodError: undefined method `compute' for nil:NilClass'

Same thing happens if I add the sale price using 'all_variants = true' or 'all_variants = false'

The problem seems to be with the master variant. If I put on sale every variant in a product except the master then it works....but in not the expected behavior, following the extensions use instructions doesn't work.

**Comment by modded-nate** [comment]
?
